cask 'dafont-walkway' do
    version :latest # created_at: 2005-12-31 00:00:00
    sha256 '7ce94e6b5167c5044b48abfd992cc9ac31ac51600490d32d2293e652f6004ab9'

    url 'http://dl.dafont.com/dl/?f=walkway'
    name 'Walkway'
    homepage 'http://www.dafont.com/walkway.font'
    license :unknown # TODO: change license and remove this comment; ':unknown' is a machine-generated placeholder

    font 'Walkway Black RevOblique.ttf'
    font 'Walkway Black.ttf'
    font 'Walkway Bold RevOblique.ttf'
    font 'Walkway Bold.ttf'
    font 'Walkway Condensed Bold.ttf'
    font 'Walkway Condensed SemiBold.ttf'
    font 'Walkway Condensed.ttf'
    font 'Walkway Expand Black.ttf'
    font 'Walkway Expand Bold.ttf'
    font 'Walkway Expand RevOblique.ttf'
    font 'Walkway Expand SemiBold.ttf'
    font 'Walkway Expand UltraBold.ttf'
    font 'Walkway Expand.ttf'
    font 'Walkway Oblique Black.ttf'
    font 'Walkway Oblique Bold.ttf'
    font 'Walkway Oblique Expand.ttf'
    font 'Walkway Oblique SemiBold.ttf'
    font 'Walkway Oblique UltraBold.ttf'
    font 'Walkway Oblique.ttf'
    font 'Walkway RevOblique.ttf'
    font 'Walkway rounded.ttf'
    font 'Walkway SemiBold RevOblique.ttf'
    font 'Walkway SemiBold.ttf'
    font 'Walkway UltraBold RevOblique.ttf'
    font 'Walkway UltraBold.ttf'
    font 'Walkway UltraCondensed Bold.ttf'
    font 'Walkway UltraCondensed Semi.ttf'
    font 'Walkway UltraCondensed.ttf'
    font 'Walkway UltraExpand Bold.ttf'
    font 'Walkway UltraExpand SemiBold.ttf'
    font 'Walkway UltraExpand.ttf'
end