cask 'dafont-buchanan' do
    version :latest # created_at: 2016-06-19 00:00:00
    sha256 '346066939daa21c3ec37829c0b2429145ad1e97acf6ce395046866bf1e521ce6'

    url 'http://dl.dafont.com/dl/?f=buchanan'
    name 'Buchanan'
    homepage 'http://www.dafont.com/buchanan.font'

    font 'buchanan.ttf'
    font 'buchanan3d.ttf'
    font 'buchanan3dital.ttf'
    font 'buchananacad.ttf'
    font 'buchananacadital.ttf'
    font 'buchananbold.ttf'
    font 'buchananboldital.ttf'
    font 'buchananchrome.ttf'
    font 'buchananchromeital.ttf'
    font 'buchanancond.ttf'
    font 'buchanancondital.ttf'
    font 'buchananexpand.ttf'
    font 'buchananexpandital.ttf'
    font 'buchanangrad.ttf'
    font 'buchanangradital.ttf'
    font 'buchananhalf.ttf'
    font 'buchananhalfital.ttf'
    font 'buchananital.ttf'
    font 'buchananlaser.ttf'
    font 'buchananlaserital.ttf'
    font 'buchananleft.ttf'
    font 'buchananout.ttf'
    font 'buchananoutital.ttf'
    font 'buchananpunch.ttf'
    font 'buchananpunchital.ttf'
    font 'buchananrotal.ttf'
    font 'buchanansemital.ttf'
    font 'buchanansuperital.ttf'
    font 'buchanantitle.ttf'
    font 'buchanantitleital.ttf'
end