cask 'dafont-quickening' do
    version :latest # created_at: 2014-08-05 00:00:00
    sha256 '9bb399434a7f950df3a9bfad2169e5564bfe186e6be2c07b237aa2f230e7d592'

    url 'http://dl.dafont.com/dl/?f=quickening'
    name 'Quickening'
    homepage 'http://www.dafont.com/quickening.font'

    font 'quickening.ttf'
    font 'quickening3d.ttf'
    font 'quickening3dital.ttf'
    font 'quickeningchrome.ttf'
    font 'quickeningchromeital.ttf'
    font 'quickeningcond.ttf'
    font 'quickeningcondital.ttf'
    font 'quickeningcondleft.ttf'
    font 'quickeningexpand.ttf'
    font 'quickeningexpandital.ttf'
    font 'quickeningextracond.ttf'
    font 'quickeningextracondital.ttf'
    font 'quickeninggrad.ttf'
    font 'quickeninggradital.ttf'
    font 'quickeninghalf.ttf'
    font 'quickeninghalfital.ttf'
    font 'quickeningital.ttf'
    font 'quickeninglaser.ttf'
    font 'quickeninglaserital.ttf'
    font 'quickeningleft.ttf'
    font 'quickeningout.ttf'
    font 'quickeningoutital.ttf'
    font 'quickeningplat.ttf'
    font 'quickeningplatital.ttf'
end