cask 'dafont-republika' do
    version :latest # created_at: 2005-12-31 00:00:00
    sha256 '2aa2f801145769c5c6d0b2e627ba946c5a0a1a09bc337c365243dc17b644b91e'

    url 'http://dl.dafont.com/dl/?f=republika'
    name 'Republika'
    homepage 'http://www.dafont.com/republika.font'
    license :unknown # TODO: change license and remove this comment; ':unknown' is a machine-generated placeholder

    font 'REP2CN__.ttf'
    font 'REP2CNI_.ttf'
    font 'REP2EXP_.ttf'
    font 'REP2EXPI.ttf'
    font 'REP3CN__.ttf'
    font 'REP3CNI_.ttf'
    font 'REP3EXP_.ttf'
    font 'REP3EXPI.ttf'
    font 'REP4CN__.ttf'
    font 'REP4CNI_.ttf'
    font 'REP4EXP_.ttf'
    font 'REP4EXPI.ttf'
    font 'REP5CN__.ttf'
    font 'REP5CNI_.ttf'
    font 'REP5EXP_.ttf'
    font 'REP5EXPI.ttf'
    font 'REPKCN__.ttf'
    font 'REPKCNI_.ttf'
    font 'REPKEXP_.ttf'
    font 'REPKEXPI.ttf'
    font 'REPUB___.ttf'
    font 'REPUB2__.ttf'
    font 'REPUB2I_.ttf'
    font 'REPUB3__.ttf'
    font 'REPUB3I_.ttf'
    font 'REPUB4__.ttf'
    font 'REPUB4I_.ttf'
    font 'REPUB5__.ttf'
    font 'REPUB5I_.ttf'
    font 'REPUBI__.ttf'
    font 'REPUBLK_.ttf'
    font 'REPUBLKI.ttf'
    font 'REPUCN__.ttf'
    font 'REPUCNI_.ttf'
    font 'REPUEXP_.ttf'
    font 'REPUEXPI.ttf'
    font 'REPUSK__.ttf'
    font 'REPUSKI_.ttf'
end