cask 'dafont-northstar' do
    version :latest # created_at: 2014-07-20 00:00:00
    sha256 '9e0379a8a20a1d466f53b40d85086bc95d8ca35240b2a4a6dd0f2274491b368d'

    url 'http://dl.dafont.com/dl/?f=northstar'
    name 'Northstar'
    homepage 'http://www.dafont.com/northstar.font'

    font 'northstar.ttf'
    font 'northstar3d.ttf'
    font 'northstar3dital.ttf'
    font 'northstarbold.ttf'
    font 'northstarboldital.ttf'
    font 'northstarchrome.ttf'
    font 'northstarchromeital.ttf'
    font 'northstarcond.ttf'
    font 'northstarcondital.ttf'
    font 'northstarexpand.ttf'
    font 'northstarexpandital.ttf'
    font 'northstargrad.ttf'
    font 'northstargradital.ttf'
    font 'northstarhalf.ttf'
    font 'northstarhalfital.ttf'
    font 'northstarital.ttf'
    font 'northstarlaser.ttf'
    font 'northstarlaserital.ttf'
    font 'northstarleft.ttf'
    font 'northstarout.ttf'
    font 'northstaroutital.ttf'
    font 'northstarsemital.ttf'
    font 'northstarsuperital.ttf'
end