cask 'dafont-quickstrike' do
    version :latest # created_at: 2005-12-31 00:00:00
    sha256 '78d8637d4836323a5143666a91a132085ff021ba76280e929258ae7acbeed96e'

    url 'http://dl.dafont.com/dl/?f=quickstrike'
    name 'Quick Strike + Tech + Gear + Mark'
    homepage 'http://www.dafont.com/quickstrike.font'

    font 'quickgear/Qgear2.ttf'
    font 'quickgear/Qgear2c.ttf'
    font 'quickgear/Qgear2ci.ttf'
    font 'quickgear/Qgear2i.ttf'
    font 'quickgear/Qgear2s.ttf'
    font 'quickgear/Qgear2si.ttf'
    font 'quickgear/Qgear2sic.ttf'
    font 'quickmark/qmark.ttf'
    font 'quickmark/qmarkc.ttf'
    font 'quickmark/qmarkci.ttf'
    font 'quickmark/qmarkcs.ttf'
    font 'quickmark/qmarkcsi.ttf'
    font 'quickmark/qmarki.ttf'
    font 'quickmark/qmarks.ttf'
    font 'quickmark/qmarksi.ttf'
    font 'quickquick/qqv2.ttf'
    font 'quickquick/qqv2b.ttf'
    font 'quickquick/qqv2c.ttf'
    font 'quickquick/qqv2ci.ttf'
    font 'quickquick/qqv2i.ttf'
    font 'quickquick/qqv2s.ttf'
    font 'quickquick/qqv2sic.ttf'
    font 'quickstrike/QSBM.FON'
    font 'quickstrike/qstrike2.ttf'
    font 'quickstrike/qstrike2c.ttf'
    font 'quickstrike/qstrike2i.ttf'
    font 'quickstrike/qstrike2ic.ttf'
    font 'quickstrike/qstrike2s.ttf'
    font 'quickstrike/qstrike2si.ttf'
    font 'quickstrike/qstrike2sic.ttf'
    font 'quicktech/Qtech2.ttf'
    font 'quicktech/Qtech2b.ttf'
    font 'quicktech/Qtech2bi.ttf'
    font 'quicktech/Qtech2c.ttf'
    font 'quicktech/Qtech2ci.ttf'
    font 'quicktech/Qtech2i.ttf'
    font 'quicktech/Qtech2s.ttf'
    font 'quicktech/Qtech2si.ttf'
end