cask 'dafont-tokyo-drifter' do
    version :latest # created_at: 2016-01-28 00:00:00
    sha256 'ac19cdcf0d0536417750cb95fba1e084e9087ab9c128578de6bd53268622e2b7'

    url 'http://dl.dafont.com/dl/?f=tokyo_drifter'
    name 'Tokyo Drifter'
    homepage 'http://www.dafont.com/tokyo-drifter.font'

    font 'tokyodrifter.ttf'
    font 'tokyodrifter3d.ttf'
    font 'tokyodrifterchrome.ttf'
    font 'tokyodriftercond.ttf'
    font 'tokyodriftercondital.ttf'
    font 'tokyodrifterengrave.ttf'
    font 'tokyodrifterexpand.ttf'
    font 'tokyodrifterexpandital.ttf'
    font 'tokyodriftergrad.ttf'
    font 'tokyodrifterhalf.ttf'
    font 'tokyodrifterital.ttf'
    font 'tokyodrifterlaser.ttf'
    font 'tokyodrifterlaserital.ttf'
    font 'tokyodrifterleft.ttf'
    font 'tokyodrifterout.ttf'
    font 'tokyodrifterpunch.ttf'
    font 'tokyodriftersemital.ttf'
    font 'tokyodrifterstaight.ttf'
    font 'tokyodrifterstaightcond.ttf'
    font 'tokyodrifterstaightexpand.ttf'
    font 'tokyodriftersuperital.ttf'
end