cask 'dafont-federal-escort' do
    version :latest # created_at: 2014-01-06 00:00:00
    sha256 'e7f907818b298c886f338d1b74bfae51965397fb410628d42fa1bda8a872be40'

    url 'http://dl.dafont.com/dl/?f=federal_escort'
    name 'Federal Escort'
    homepage 'http://www.dafont.com/federal-escort.font'

    font 'federalescort.ttf'
    font 'federalescort3d.ttf'
    font 'federalescort3dital.ttf'
    font 'federalescortbullet.ttf'
    font 'federalescortbulletital.ttf'
    font 'federalescortchrome.ttf'
    font 'federalescortchromeital.ttf'
    font 'federalescortcond.ttf'
    font 'federalescortcondital.ttf'
    font 'federalescortexpand.ttf'
    font 'federalescortexpandital.ttf'
    font 'federalescorthalf.ttf'
    font 'federalescorthalfital.ttf'
    font 'federalescortital.ttf'
    font 'federalescortlaser.ttf'
    font 'federalescortlaserital.ttf'
    font 'federalescortleft.ttf'
    font 'federalescortout.ttf'
    font 'federalescortoutital.ttf'
    font 'federalescortscan.ttf'
    font 'federalescortscanital.ttf'
    font 'federalescortsemiital.ttf'
end