cask 'dafont-give-a-hoot' do
    version :latest # created_at: 2016-02-04 00:00:00
    sha256 'b756ea034f9417ababfcdfc796bcdd7863d54d9b70693ee5a756349bc971526a'

    url 'http://dl.dafont.com/dl/?f=give_a_hoot'
    name 'Give A Hoot'
    homepage 'http://www.dafont.com/give-a-hoot.font'
    license :unknown # TODO: change license and remove this comment; ':unknown' is a machine-generated placeholder

    font 'GiveAHoot.otf'
    font 'GiveAHootBd.otf'
    font 'GiveAHootBdExt.otf'
    font 'GiveAHootBdExtObl.otf'
    font 'GiveAHootBdObl.otf'
    font 'GiveAHootBk.otf'
    font 'GiveAHootBkExt.otf'
    font 'GiveAHootBkExtObl.otf'
    font 'GiveAHootBkObl.otf'
    font 'GiveAHootBlk.otf'
    font 'GiveAHootBlkExt.otf'
    font 'GiveAHootBlkExtObl.otf'
    font 'GiveAHootBlkObl.otf'
    font 'GiveAHootDP.otf'
    font 'GiveAHootDPExt.otf'
    font 'GiveAHootDPExtObl.otf'
    font 'GiveAHootDPObl.otf'
    font 'GiveAHootExBd.otf'
    font 'GiveAHootExBdExt.otf'
    font 'GiveAHootExBdExtObl.otf'
    font 'GiveAHootExBdObl.otf'
    font 'GiveAHootExt.otf'
    font 'GiveAHootExtObl.otf'
    font 'GiveAHootObl.otf'
    font 'GiveAHootSbd.otf'
    font 'GiveAHootSbdExt.otf'
    font 'GiveAHootSbdExtObl.otf'
    font 'GiveAHootSbdObl.otf'
end