cask 'dafont-battleworld' do
    version :latest # created_at: 2016-03-14 00:00:00
    sha256 '7f1e522757ee975fcb10d4c13c14d02a795a52b21ada033b324a16099acf75fd'

    url 'http://dl.dafont.com/dl/?f=battleworld'
    name 'Battleworld'
    homepage 'http://www.dafont.com/battleworld.font'

    font 'battleworld.ttf'
    font 'battleworld3d.ttf'
    font 'battleworld3dital.ttf'
    font 'battleworldcond.ttf'
    font 'battleworldcondital.ttf'
    font 'battleworldengrave.ttf'
    font 'battleworldengraveital.ttf'
    font 'battleworldexpand.ttf'
    font 'battleworldexpandital.ttf'
    font 'battleworldital.ttf'
    font 'battleworldleft.ttf'
    font 'battleworldout.ttf'
    font 'battleworldoutital.ttf'
    font 'battleworldpunch.ttf'
    font 'battleworldpunchital.ttf'
    font 'battleworldsemital.ttf'
    font 'battleworldsuperital.ttf'
    font 'battleworldtitle.ttf'
    font 'battleworldtitleital.ttf'
    font 'battleworldxtraexpand.ttf'
    font 'battleworldxtraexpandital.ttf'
end