cask 'dafont-united-planets' do
    version :latest # created_at: 2014-01-09 00:00:00
    sha256 'df0fa1aa5d23ba6e5f6db78f10d10f54eb698622473ae6ca6812a56e3f798c3a'

    url 'http://dl.dafont.com/dl/?f=united_planets'
    name 'United Planets'
    homepage 'http://www.dafont.com/united-planets.font'

    font 'unitedplanets.ttf'
    font 'unitedplanets3d.ttf'
    font 'unitedplanets3dital.ttf'
    font 'unitedplanetsacad.ttf'
    font 'unitedplanetsacadital.ttf'
    font 'unitedplanetsbold.ttf'
    font 'unitedplanetsboldital.ttf'
    font 'unitedplanetscond.ttf'
    font 'unitedplanetscondital.ttf'
    font 'unitedplanetsexpand.ttf'
    font 'unitedplanetsexpandital.ttf'
    font 'unitedplanetsgrad.ttf'
    font 'unitedplanetsgradital.ttf'
    font 'unitedplanetshalf.ttf'
    font 'unitedplanetshalfital.ttf'
    font 'unitedplanetsital.ttf'
    font 'unitedplanetsleft.ttf'
    font 'unitedplanetsout.ttf'
    font 'unitedplanetsoutital.ttf'
    font 'unitedplanetssemibold.ttf'
    font 'unitedplanetssemiboldital.ttf'
end