cask 'dafont-oramac' do
    version :latest # created_at: 2005-12-31 00:00:00 and updated_at: 2016-06-09 00:00:00
    sha256 'cc1cedf84032442667d889b1ebcce6399ac00034ffd9f1dd152d1c205fcf88b4'

    url 'http://dl.dafont.com/dl/?f=oramac'
    name 'Oramac'
    homepage 'http://www.dafont.com/oramac.font'
    license :unknown # TODO: change license and remove this comment; ':unknown' is a machine-generated placeholder

    font 'oramac.ttf'
    font 'oramac3d.ttf'
    font 'oramac3dital.ttf'
    font 'oramacchrome.ttf'
    font 'oramacchromeital.ttf'
    font 'oramaccond.ttf'
    font 'oramaccondital.ttf'
    font 'oramacengrave.ttf'
    font 'oramacengraveital.ttf'
    font 'oramacexpand.ttf'
    font 'oramacexpandital.ttf'
    font 'oramacgrad.ttf'
    font 'oramacgradital.ttf'
    font 'oramachalf.ttf'
    font 'oramachalfital.ttf'
    font 'oramacital.ttf'
    font 'oramaclaser.ttf'
    font 'oramaclaserital.ttf'
    font 'oramacleft.ttf'
    font 'oramaclight.ttf'
    font 'oramaclightital.ttf'
    font 'oramacpunch.ttf'
    font 'oramacpunchital.ttf'
    font 'oramacsemital.ttf'
    font 'oramacshadow.ttf'
    font 'oramacshadowital.ttf'
    font 'oramacsuperital.ttf'
    font 'oramacxtracond.ttf'
    font 'oramacxtracondital.ttf'
end