cask 'dafont-montroc' do
    version :latest # created_at: 2015-06-30 00:00:00
    sha256 'f3659939ea4f710099bf38e7c938d480ceb6cd5fef44c2bcafc151cbfc01b81f'

    url 'http://dl.dafont.com/dl/?f=montroc'
    name 'Montroc'
    homepage 'http://www.dafont.com/montroc.font'

    font 'montroc.ttf'
    font 'montroc3d.ttf'
    font 'montroc3dital.ttf'
    font 'montrocacad.ttf'
    font 'montrocacadital.ttf'
    font 'montroccond.ttf'
    font 'montroccondital.ttf'
    font 'montrocexpand.ttf'
    font 'montrocexpandital.ttf'
    font 'montrocgrad.ttf'
    font 'montrocgradital.ttf'
    font 'montrochalf.ttf'
    font 'montrochalfital.ttf'
    font 'montrocital.ttf'
    font 'montroclaser.ttf'
    font 'montroclaserital.ttf'
    font 'montrocleft.ttf'
    font 'montrocout.ttf'
    font 'montrocoutital.ttf'
    font 'montrocsemital.ttf'
    font 'montrocsuperital.ttf'
end