cask 'dafont-gemina-2' do
    version :latest # created_at: 2013-01-25 00:00:00 and updated_at: 2015-05-02 00:00:00
    sha256 'f82162fdedd6056ebf5efada7da4caaf38d9eda8bb9c4d585d804d2d8c35983a'

    url 'http://dl.dafont.com/dl/?f=gemina_2'
    name 'Gemina 2'
    homepage 'http://www.dafont.com/gemina-2.font'

    font 'gemina2.ttf'
    font 'gemina23d.ttf'
    font 'gemina23dital.ttf'
    font 'gemina2acad.ttf'
    font 'gemina2acadital.ttf'
    font 'gemina2cond.ttf'
    font 'gemina2condital.ttf'
    font 'gemina2expand.ttf'
    font 'gemina2expandital.ttf'
    font 'gemina2grad.ttf'
    font 'gemina2gradital.ttf'
    font 'gemina2half.ttf'
    font 'gemina2halfital.ttf'
    font 'gemina2ital.ttf'
    font 'gemina2laser.ttf'
    font 'gemina2laser3d.ttf'
    font 'gemina2laser3dital.ttf'
    font 'gemina2laserital.ttf'
    font 'gemina2laserleft.ttf'
    font 'gemina2left.ttf'
    font 'gemina2semital.ttf'
end