cask 'dafont-banshee-pilot' do
    version :latest # created_at: 2016-04-16 00:00:00
    sha256 'a40823d6f7d8d890c9ea2a72dd0ee0e79d3e8d63d455bc1dbf0dd978372a043f'

    url 'http://dl.dafont.com/dl/?f=banshee_pilot'
    name 'Banshee Pilot'
    homepage 'http://www.dafont.com/banshee-pilot.font'
    license :unknown # TODO: change license and remove this comment; ':unknown' is a machine-generated placeholder

    font 'bansheepilot.ttf'
    font 'bansheepilot3d.ttf'
    font 'bansheepilot3dital.ttf'
    font 'bansheepilotblack.ttf'
    font 'bansheepilotblackital.ttf'
    font 'bansheepilotbold.ttf'
    font 'bansheepilotboldital.ttf'
    font 'bansheepilotcond.ttf'
    font 'bansheepilotcondital.ttf'
    font 'bansheepilotengrave.ttf'
    font 'bansheepilotengraveital.ttf'
    font 'bansheepilotexpand.ttf'
    font 'bansheepilotexpandital.ttf'
    font 'bansheepilotgrad.ttf'
    font 'bansheepilotgradital.ttf'
    font 'bansheepilothalf.ttf'
    font 'bansheepilothalfital.ttf'
    font 'bansheepilotital.ttf'
    font 'bansheepilotlaser.ttf'
    font 'bansheepilotlaserital.ttf'
    font 'bansheepilotleft.ttf'
    font 'bansheepilotpunch.ttf'
    font 'bansheepilotpunchital.ttf'
    font 'bansheepilotsemital.ttf'
    font 'bansheepilotsuperital.ttf'
    font 'bansheepilottitle.ttf'
    font 'bansheepilottitleital.ttf'
end