cask 'dafont-butch-sundance' do
    version :latest # created_at: 2013-06-16 00:00:00
    sha256 '119b74e85c111270ac3b69c5e6f0217264baa3357892accb7c57d0b8a4501761'

    url 'http://dl.dafont.com/dl/?f=butch_sundance'
    name 'Butch &amp; Sundance'
    homepage 'http://www.dafont.com/butch-sundance.font'

    font 'butchsundance.ttf'
    font 'butchsundance3d.ttf'
    font 'butchsundance3dital.ttf'
    font 'butchsundancebold.ttf'
    font 'butchsundanceboldital.ttf'
    font 'butchsundancebullet.ttf'
    font 'butchsundancebulletital.ttf'
    font 'butchsundancecond.ttf'
    font 'butchsundancecondital.ttf'
    font 'butchsundanceexpand.ttf'
    font 'butchsundanceexpandital.ttf'
    font 'butchsundancegrad.ttf'
    font 'butchsundancegradchrome.ttf'
    font 'butchsundancegradchromeital.ttf'
    font 'butchsundancegradital.ttf'
    font 'butchsundanceital.ttf'
    font 'butchsundanceleft.ttf'
    font 'butchsundanceplat.ttf'
    font 'butchsundanceplatital.ttf'
    font 'butchsundancetone.ttf'
    font 'butchsundancetoneital.ttf'
end