cask 'dafont-gemina' do
    version :latest # created_at: 2011-09-12 00:00:00 and updated_at: 2015-05-09 00:00:00
    sha256 'cb35d182778afcea10bdb44378b43434a2f7a9a243cf3a74c3153d3914a36967'

    url 'http://dl.dafont.com/dl/?f=gemina'
    name 'Gemina'
    homepage 'http://www.dafont.com/gemina.font'

    font 'gemina.ttf'
    font 'gemina3d.ttf'
    font 'gemina3dital.ttf'
    font 'geminaacad.ttf'
    font 'geminaacadital.ttf'
    font 'geminacond.ttf'
    font 'geminacondital.ttf'
    font 'geminaexpand.ttf'
    font 'geminaexpandital.ttf'
    font 'geminagrad.ttf'
    font 'geminagradital.ttf'
    font 'geminahalf.ttf'
    font 'geminahalfital.ttf'
    font 'geminaital.ttf'
    font 'geminalaser.ttf'
    font 'geminalaser3d.ttf'
    font 'geminalaser3dital.ttf'
    font 'geminalaserital.ttf'
    font 'geminalaserleft.ttf'
    font 'geminaleft.ttf'
    font 'geminasemital.ttf'
end