cask 'dafont-zyborgs' do
    version :latest # created_at: 2005-12-31 00:00:00 and updated_at: 2016-05-06 00:00:00
    sha256 '32e80bf1d51d0222c6fb85357a8d3a5f8a130a960157cef01f0bcd74257a88cb'

    url 'http://dl.dafont.com/dl/?f=zyborgs'
    name 'Zyborgs'
    homepage 'http://www.dafont.com/zyborgs.font'

    font 'zyborgs.ttf'
    font 'zyborgs3d.ttf'
    font 'zyborgs3dital.ttf'
    font 'zyborgsbold.ttf'
    font 'zyborgsboldital.ttf'
    font 'zyborgschrome.ttf'
    font 'zyborgschromeital.ttf'
    font 'zyborgscond.ttf'
    font 'zyborgscondital.ttf'
    font 'zyborgsengrave.ttf'
    font 'zyborgsengraveital.ttf'
    font 'zyborgsexpand.ttf'
    font 'zyborgsexpandital.ttf'
    font 'zyborgsgrad.ttf'
    font 'zyborgsgradital.ttf'
    font 'zyborgshalf.ttf'
    font 'zyborgshalfital.ttf'
    font 'zyborgsital.ttf'
    font 'zyborgslaser.ttf'
    font 'zyborgslaserital.ttf'
    font 'zyborgsleft.ttf'
    font 'zyborgsout.ttf'
    font 'zyborgsoutital.ttf'
    font 'zyborgspunch.ttf'
    font 'zyborgspunchital.ttf'
    font 'zyborgssemital.ttf'
    font 'zyborgssuperital.ttf'
    font 'zyborgstitle.ttf'
    font 'zyborgstitleital.ttf'
end