cask 'dafont-interceptor' do
    version :latest # created_at: 2008-05-17 00:00:00 and updated_at: 2016-04-14 00:00:00
    sha256 'a313ded692a4d5446f0009e297234ac0f45ca52a0c3d2a42b0ed020cc18165d1'

    url 'http://dl.dafont.com/dl/?f=interceptor'
    name 'Interceptor'
    homepage 'http://www.dafont.com/interceptor.font'
    license :unknown # TODO: change license and remove this comment; ':unknown' is a machine-generated placeholder

    font 'interceptor.ttf'
    font 'interceptor3d.ttf'
    font 'interceptor3dital.ttf'
    font 'interceptorbold.ttf'
    font 'interceptorboldexpand.ttf'
    font 'interceptorboldexpandital.ttf'
    font 'interceptorboldital.ttf'
    font 'interceptorchrome.ttf'
    font 'interceptorchromeital.ttf'
    font 'interceptorcond.ttf'
    font 'interceptorcondital.ttf'
    font 'interceptorengrave.ttf'
    font 'interceptorengraveital.ttf'
    font 'interceptorexpand.ttf'
    font 'interceptorexpandital.ttf'
    font 'interceptorgrad.ttf'
    font 'interceptorgradital.ttf'
    font 'interceptorhalf.ttf'
    font 'interceptorhalfital.ttf'
    font 'interceptorital.ttf'
    font 'interceptorleft.ttf'
    font 'interceptorpunch.ttf'
    font 'interceptorpunchital.ttf'
    font 'interceptorsemital.ttf'
    font 'interceptorsuperital.ttf'
    font 'interceptortitle.ttf'
    font 'interceptortitleital.ttf'
end