cask 'dafont-passion-sans-pd' do
    version :latest # created_at: 2011-11-21 00:00:00
    sha256 '9e2d078bf11c355e5c64f6b708dcf8ca8a0564ca6c0e9c9a0b27f056fc12f4cc'

    url 'http://dl.dafont.com/dl/?f=passion_sans_pd'
    name 'Passion Sans'
    homepage 'http://www.dafont.com/passion-sans-pd.font'

    font 'PassionSansPDaa-Hairline.ttf'
    font 'PassionSansPDab-HairlineI 2.ttf'
    font 'PassionSansPDab-HairlineIta.ttf'
    font 'PassionSansPDac-Light.ttf'
    font 'PassionSansPDad-LightItalic.ttf'
    font 'PassionSansPDae-Book.ttf'
    font 'PassionSansPDaf-BookItalic.ttf'
    font 'PassionSansPDag-Regular.ttf'
    font 'PassionSansPDah-RegularItal.ttf'
    font 'PassionSansPDai-SemiBold.ttf'
    font 'PassionSansPDaj-SemiBoldIta.ttf'
    font 'PassionSansPDak-Bold.ttf'
    font 'PassionSansPDal-BoldItalic.ttf'
    font 'PassionSansPDam-Heavy.ttf'
    font 'PassionSansPDan-HeavyItalic.ttf'
    font 'PassionSansPDao-ExtraBold.ttf'
    font 'PassionSansPDap-ExtraBoldIt.ttf'
    font 'PassionSansPDaq-Black.ttf'
    font 'PassionSansPDar-BlackItalic.ttf'
    font 'PassionSansPDba-HairlineSma.ttf'
    font 'PassionSansPDbc-LightSmallC.ttf'
    font 'PassionSansPDbe-BookSmallCa.ttf'
    font 'PassionSansPDbg-RegularSmal.ttf'
    font 'PassionSansPDbi-SemiBoldSma.ttf'
    font 'PassionSansPDbk-BoldSmallCa.ttf'
    font 'PassionSansPDca-OutlineLigh.ttf'
    font 'PassionSansPDcb-OutlineHeav.ttf'
    font 'PassionSansPDcc-Contour.ttf'
    font 'PassionSansPDcd-AccentOuter.ttf'
    font 'PassionSansPDce-AccentCente.ttf'
end