cask 'dafont-gobold' do
    version :latest # created_at: 2013-09-07 00:00:00 and updated_at: 2014-02-27 00:00:00
    sha256 '4e8bb2687502ad6f299a6ff6bfd719c75bd5a5c6d32d8e570829b2a5cbb30a01'

    url 'http://dl.dafont.com/dl/?f=gobold'
    name 'Gobold'
    homepage 'http://www.dafont.com/gobold.font'

    font 'Gobold Bold Italic.ttf'
    font 'Gobold Bold.ttf'
    font 'Gobold Extra1 Italic.ttf'
    font 'Gobold Extra1.ttf'
    font 'Gobold High Bold Italic.ttf'
    font 'Gobold High Bold.ttf'
    font 'Gobold High Italic.ttf'
    font 'Gobold High Thin Italic.ttf'
    font 'Gobold High Thin.ttf'
    font 'Gobold High.ttf'
    font 'Gobold Hollow Bold Italic.ttf'
    font 'Gobold Hollow Bold.ttf'
    font 'Gobold Hollow Italic.ttf'
    font 'Gobold Hollow.ttf'
    font 'Gobold Italic.ttf'
    font 'Gobold Light Italic.ttf'
    font 'Gobold Light.ttf'
    font 'Gobold Lowplus Italic.ttf'
    font 'Gobold Lowplus.ttf'
    font 'Gobold Regular.ttf'
    font 'Gobold Thin Italic.ttf'
    font 'Gobold Thin.ttf'
    font 'Gobold Uplow Italic.ttf'
    font 'Gobold Uplow.ttf'
end