cask 'dafont-annapolis' do
    version :latest # created_at: 2016-02-14 00:00:00
    sha256 '0aaeb94020e77f149eb628877ef98ae0c20d79452b7ec93f34cd9c478c931a86'

    url 'http://dl.dafont.com/dl/?f=annapolis'
    name 'Annapolis'
    homepage 'http://www.dafont.com/annapolis.font'

    font 'annapolis.ttf'
    font 'annapolis3d.ttf'
    font 'annapolis3dital.ttf'
    font 'annapolisbevel.ttf'
    font 'annapolisbevelital.ttf'
    font 'annapolisbullet.ttf'
    font 'annapolisbulletital.ttf'
    font 'annapolischrome.ttf'
    font 'annapolischromeital.ttf'
    font 'annapoliscond.ttf'
    font 'annapoliscondital.ttf'
    font 'annapolisemiital.ttf'
    font 'annapolisexpand.ttf'
    font 'annapolisexpandital.ttf'
    font 'annapolisgrad.ttf'
    font 'annapolisgradital.ttf'
    font 'annapolishalf.ttf'
    font 'annapolishalfital.ttf'
    font 'annapolisital.ttf'
    font 'annapolislaser.ttf'
    font 'annapolislaserital.ttf'
    font 'annapolisleft.ttf'
    font 'annapolislowercase.ttf'
    font 'annapolislowercasecond.ttf'
    font 'annapolislowercasecondital.ttf'
    font 'annapolislowercaseital.ttf'
    font 'annapolislowercaseout.ttf'
    font 'annapolislowercaseoutital.ttf'
    font 'annapolislowercasesemital.ttf'
    font 'annapolislowercasexpand.ttf'
    font 'annapolislowercasexpandital.ttf'
    font 'annapolisout.ttf'
    font 'annapolisoutital.ttf'
    font 'annapolispunch.ttf'
    font 'annapolispunchital.ttf'
    font 'annapolissuperital.ttf'
end