cask 'dafont-alien-league' do
    version :latest # created_at: 2005-12-31 00:00:00 and updated_at: 2013-09-02 00:00:00
    sha256 'c416cc552361fd64723bfdf924012540040b463cf7b8ce689c9a10540932b252'

    url 'http://dl.dafont.com/dl/?f=alien_league'
    name 'Alien League'
    homepage 'http://www.dafont.com/alien-league.font'

    font 'alienleague.ttf'
    font 'alienleague3d.ttf'
    font 'alienleague3dital.ttf'
    font 'alienleaguebold.ttf'
    font 'alienleaguebolditalic.ttf'
    font 'alienleaguecond.ttf'
    font 'alienleaguecondital.ttf'
    font 'alienleagueexpand.ttf'
    font 'alienleaguegrad.ttf'
    font 'alienleaguegradbold.ttf'
    font 'alienleagueii.ttf'
    font 'alienleagueii3d.ttf'
    font 'alienleagueii3dital.ttf'
    font 'alienleagueiibold.ttf'
    font 'alienleagueiiboldital.ttf'
    font 'alienleagueiicond.ttf'
    font 'alienleagueiicondital.ttf'
    font 'alienleagueiiexpand.ttf'
    font 'alienleagueiiexpandital.ttf'
    font 'alienleagueiigrad.ttf'
    font 'alienleagueiigradbold.ttf'
    font 'alienleagueiiital.ttf'
    font 'alienleagueiileft.ttf'
    font 'alienleagueiiout.ttf'
    font 'alienleagueital.ttf'
    font 'alienleagueleft.ttf'
    font 'alienleagueout.ttf'
end