cask 'dafont-kingsbridge' do
    version :latest # created_at: 2014-11-16 00:00:00
    sha256 'e16f13c0aff50a2d1742a49fdc8cf9c97593778cd939af1af67593947b3fdb14'

    url 'http://dl.dafont.com/dl/?f=kingsbridge'
    name 'Kingsbridge'
    homepage 'http://www.dafont.com/kingsbridge.font'

    font 'kingsbridge bd it.ttf'
    font 'kingsbridge bd.ttf'
    font 'kingsbridge bk it.ttf'
    font 'kingsbridge bk.ttf'
    font 'kingsbridge cd bd it.ttf'
    font 'kingsbridge cd bd.ttf'
    font 'kingsbridge cd bk it.ttf'
    font 'kingsbridge cd bk.ttf'
    font 'kingsbridge cd el it.ttf'
    font 'kingsbridge cd el.ttf'
    font 'kingsbridge cd lt it.ttf'
    font 'kingsbridge cd lt.ttf'
    font 'kingsbridge cd rg it.ttf'
    font 'kingsbridge cd rg.ttf'
    font 'kingsbridge cd sb it.ttf'
    font 'kingsbridge cd sb.ttf'
    font 'kingsbridge cd ul it.ttf'
    font 'kingsbridge cd ul.ttf'
    font 'kingsbridge el it.ttf'
    font 'kingsbridge el.ttf'
    font 'kingsbridge ex bd it.ttf'
    font 'kingsbridge ex bd.ttf'
    font 'kingsbridge ex bk it.ttf'
    font 'kingsbridge ex bk.ttf'
    font 'kingsbridge ex el it.ttf'
    font 'kingsbridge ex el.ttf'
    font 'kingsbridge ex lt it.ttf'
    font 'kingsbridge ex lt.ttf'
    font 'kingsbridge ex rg it.ttf'
    font 'kingsbridge ex rg.ttf'
    font 'kingsbridge ex sb it.ttf'
    font 'kingsbridge ex sb.ttf'
    font 'kingsbridge ex ul it.ttf'
    font 'kingsbridge ex ul.ttf'
    font 'kingsbridge lt it.ttf'
    font 'kingsbridge lt.ttf'
    font 'kingsbridge rg it.ttf'
    font 'kingsbridge rg.ttf'
    font 'kingsbridge sb it.ttf'
    font 'kingsbridge sb.ttf'
    font 'kingsbridge sc bd it.ttf'
    font 'kingsbridge sc bd.ttf'
    font 'kingsbridge sc bk it.ttf'
    font 'kingsbridge sc bk.ttf'
    font 'kingsbridge sc el it.ttf'
    font 'kingsbridge sc el.ttf'
    font 'kingsbridge sc lt it.ttf'
    font 'kingsbridge sc lt.ttf'
    font 'kingsbridge sc rg it.ttf'
    font 'kingsbridge sc rg.ttf'
    font 'kingsbridge sc sb it.ttf'
    font 'kingsbridge sc sb.ttf'
    font 'kingsbridge sc ul it.ttf'
    font 'kingsbridge sc ul.ttf'
    font 'kingsbridge ul it.ttf'
    font 'kingsbridge ul.ttf'
end