cask 'dafont-7th-service' do
    version :latest # created_at: 2005-12-31 00:00:00 and updated_at: 2016-02-11 00:00:00
    sha256 'f49b7a1c4c5cd92a64ab75d4502804777325e4b01febb52e6d3b5f07dae70ef0'

    url 'http://dl.dafont.com/dl/?f=7th_service'
    name '7th Service'
    homepage 'http://www.dafont.com/7th-service.font'
    license :unknown # TODO: change license and remove this comment; ':unknown' is a machine-generated placeholder

    font '7thservice.ttf'
    font '7thservice3d.ttf'
    font '7thservice3dital.ttf'
    font '7thservicebold.ttf'
    font '7thserviceboldital.ttf'
    font '7thservicechrome.ttf'
    font '7thservicechromeital.ttf'
    font '7thservicecond.ttf'
    font '7thservicecondital.ttf'
    font '7thserviceengrave.ttf'
    font '7thserviceengraveital.ttf'
    font '7thservicegrad.ttf'
    font '7thservicegradital.ttf'
    font '7thservicehalf.ttf'
    font '7thservicehalfital.ttf'
    font '7thserviceital.ttf'
    font '7thserviceleft.ttf'
    font '7thservicepunch.ttf'
    font '7thservicepunchital.ttf'
    font '7thservicesemital.ttf'
    font '7thservicesuperital.ttf'
    font '7thservicetitle.ttf'
    font '7thservicetitleital.ttf'
    font '7thservicexpand.ttf'
    font '7thservicexpandital.ttf'
end