cask 'dafont-skyhawk' do
    version :latest # created_at: 2014-05-24 00:00:00
    sha256 'cabf97feaa0970c89cc2b4e6553d7fa383f406b5ab2d013a8b3f0974ebe68f75'

    url 'http://dl.dafont.com/dl/?f=skyhawk'
    name 'Skyhawk'
    homepage 'http://www.dafont.com/skyhawk.font'

    font 'skyhawk.ttf'
    font 'skyhawk3d.ttf'
    font 'skyhawk3dital.ttf'
    font 'skyhawkchrome.ttf'
    font 'skyhawkchromeital.ttf'
    font 'skyhawkcond.ttf'
    font 'skyhawkcondital.ttf'
    font 'skyhawkexpand.ttf'
    font 'skyhawkexpandital.ttf'
    font 'skyhawkhalf.ttf'
    font 'skyhawkhalfital.ttf'
    font 'skyhawkital.ttf'
    font 'skyhawklaser.ttf'
    font 'skyhawklaserital.ttf'
    font 'skyhawkleft.ttf'
    font 'skyhawkout.ttf'
    font 'skyhawkoutital.ttf'
    font 'skyhawkplat.ttf'
    font 'skyhawkplatital.ttf'
    font 'skyhawkscan.ttf'
    font 'skyhawkscanital.ttf'
    font 'skyhawksemi.ttf'
    font 'skyhawksuperital.ttf'
end