cask 'dafont-villeray' do
    version :latest # created_at: 2016-06-19 00:00:00
    sha256 '57ad57c75736f0f1f44f95afb04438ffb3824fd437981d2cac4acb753d9e7b55'

    url 'http://dl.dafont.com/dl/?f=villeray'
    name 'Villeray'
    homepage 'http://www.dafont.com/villeray.font'
    license :unknown # TODO: change license and remove this comment; ':unknown' is a machine-generated placeholder

    font 'Villeray-Black.ttf'
    font 'Villeray-BlackItalic.ttf'
    font 'Villeray-Bold.ttf'
    font 'Villeray-BoldItalic.ttf'
    font 'Villeray-Italic.ttf'
    font 'Villeray-Light.ttf'
    font 'Villeray-LightItalic.ttf'
    font 'Villeray-Medium.ttf'
    font 'Villeray-MediumItalic.ttf'
    font 'Villeray-Regular.ttf'
    font 'Villeray-Semilight.ttf'
    font 'Villeray-SemilightItalic.ttf'
    font 'Villeray-Thin.ttf'
    font 'Villeray-ThinItalic.ttf'
    font 'Villeray-UltraBold.ttf'
    font 'Villeray-UltraBoldItalic.ttf'
    font 'VillerayRounded-Black.ttf'
    font 'VillerayRounded-BlackItalic.ttf'
    font 'VillerayRounded-Bold.ttf'
    font 'VillerayRounded-BoldItalic.ttf'
    font 'VillerayRounded-Italic.ttf'
    font 'VillerayRounded-Light.ttf'
    font 'VillerayRounded-LightItalic.ttf'
    font 'VillerayRounded-Medium.ttf'
    font 'VillerayRounded-MediumItalic.ttf'
    font 'VillerayRounded-Regular.ttf'
    font 'VillerayRounded-Semilight.ttf'
    font 'VillerayRounded-SemilightItalic.ttf'
    font 'VillerayRounded-Thin.ttf'
    font 'VillerayRounded-ThinItalic.ttf'
    font 'VillerayRounded-UltraBold.ttf'
    font 'VillerayRounded-UltraBoldItalic.ttf'
end