cask 'dafont-legion' do
    version :latest # created_at: 2005-12-31 00:00:00 and updated_at: 2015-08-22 00:00:00
    sha256 'e611f141b353b28b5f8c58b8ed02a2f51297a835dac6898e14b903ec2bf62bd7'

    url 'http://dl.dafont.com/dl/?f=legion'
    name 'Legion'
    homepage 'http://www.dafont.com/legion.font'

    font 'legion.ttf'
    font 'legion3d.ttf'
    font 'legion3dital.ttf'
    font 'legionbold.ttf'
    font 'legionboldital.ttf'
    font 'legionboldsemital.ttf'
    font 'legionbullet.ttf'
    font 'legionbulletital.ttf'
    font 'legionchrome.ttf'
    font 'legionchromeital.ttf'
    font 'legioncond.ttf'
    font 'legioncondital.ttf'
    font 'legionexpand.ttf'
    font 'legionexpandital.ttf'
    font 'legiongrad.ttf'
    font 'legiongradital.ttf'
    font 'legionhalf.ttf'
    font 'legionhalfital.ttf'
    font 'legionital.ttf'
    font 'legionlaser.ttf'
    font 'legionlaserital.ttf'
    font 'legionleft.ttf'
    font 'legionsemital.ttf'
    font 'legiontitle.ttf'
    font 'legiontitleital.ttf'
end