cask 'dafont-sdf' do
    version :latest # created_at: 2013-01-25 00:00:00 and updated_at: 2015-06-17 00:00:00
    sha256 '96a7408c35ad9e08ee5b2284b6712d0275f529e5c0fafc8600de2777f2f4d635'

    url 'http://dl.dafont.com/dl/?f=sdf'
    name 'SDF'
    homepage 'http://www.dafont.com/sdf.font'

    font 'sdf.ttf'
    font 'sdf3d.ttf'
    font 'sdf3dital.ttf'
    font 'sdfacad.ttf'
    font 'sdfacadital.ttf'
    font 'sdfbold.ttf'
    font 'sdfboldital.ttf'
    font 'sdfcond.ttf'
    font 'sdfcondital.ttf'
    font 'sdfexpand.ttf'
    font 'sdfexpandital.ttf'
    font 'sdfgrad.ttf'
    font 'sdfgradital.ttf'
    font 'sdfhalf.ttf'
    font 'sdfhalfital.ttf'
    font 'sdfital.ttf'
    font 'sdfjag.ttf'
    font 'sdfjagital.ttf'
    font 'sdflaser.ttf'
    font 'sdflaserital.ttf'
    font 'sdfleft.ttf'
    font 'sdflight.ttf'
    font 'sdflightital.ttf'
    font 'sdfrotate.ttf'
    font 'sdfsemital.ttf'
    font 'sdfsuperital.ttf'
end