cask 'dafont-rider' do
    version :latest # created_at: 2011-02-28 00:00:00
    sha256 'c8d64751a3eddf70f156e4665f210e3abc65c5ba879bb8a23f5387fd94b7a717'

    url 'http://dl.dafont.com/dl/?f=rider'
    name 'Rider'
    homepage 'http://www.dafont.com/rider.font'
    license :unknown # TODO: change license and remove this comment; ':unknown' is a machine-generated placeholder

    font 'fat_high_italic.ttf'
    font 'fat_high.ttf'
    font 'fat_highest_italic.ttf'
    font 'fat_highest.ttf'
    font 'fat_italic.ttf'
    font 'fat_wide_italic.ttf'
    font 'fat_wide.ttf'
    font 'fat_widest_italic.ttf'
    font 'fat_widest.ttf'
    font 'fat.ttf'
    font 'fatest_high_italic.ttf'
    font 'fatest_high.ttf'
    font 'fatest_highest_italic.ttf'
    font 'fatest_highest.ttf'
    font 'fatest_italic.ttf'
    font 'fatest_wide_italic.ttf'
    font 'fatest_wide.ttf'
    font 'fatest_widest_italic.ttf'
    font 'fatest_widest.ttf'
    font 'fatest.ttf'
    font 'thin_high_italic.ttf'
    font 'thin_high.ttf'
    font 'thin_highest_italic.ttf'
    font 'thin_highest.ttf'
    font 'thin_italic.ttf'
    font 'thin_wide_italic.ttf'
    font 'thin_wide.ttf'
    font 'thin_widest_italic.ttf'
    font 'thin_widest.ttf'
    font 'thin.ttf'
end