cask 'dafont-gearhead' do
    version :latest # created_at: 2013-12-17 00:00:00
    sha256 '942d535871ac45d392031814e7c2964ac73e87b9c760886ddd0703829a4c455e'

    url 'http://dl.dafont.com/dl/?f=gearhead'
    name 'Gearhead'
    homepage 'http://www.dafont.com/gearhead.font'
    license :unknown # TODO: change license and remove this comment; ':unknown' is a machine-generated placeholder

    font 'gearhead.ttf'
    font 'gearhead3d.ttf'
    font 'gearhead3dital.ttf'
    font 'gearheadacad.ttf'
    font 'gearheadacadital.ttf'
    font 'gearheadbullet.ttf'
    font 'gearheadbulletital.ttf'
    font 'gearheadchrome.ttf'
    font 'gearheadchromeital.ttf'
    font 'gearheadcond.ttf'
    font 'gearheadcondital.ttf'
    font 'gearheadengrave.ttf'
    font 'gearheadengraveital.ttf'
    font 'gearheadexpand.ttf'
    font 'gearheadexpandital.ttf'
    font 'gearheadhalf.ttf'
    font 'gearheadhalfital.ttf'
    font 'gearheadital.ttf'
    font 'gearheadlaser.ttf'
    font 'gearheadlaserital.ttf'
    font 'gearheadleft.ttf'
    font 'gearheadout.ttf'
    font 'gearheadoutital.ttf'
    font 'gearheadscan.ttf'
    font 'gearheadscanital.ttf'
end