cask 'dafont-red-rocket' do
    version :latest # created_at: 2011-11-03 00:00:00 and updated_at: 2016-03-03 00:00:00
    sha256 '6c264785e90b29f89f983d613452f3230b632cdd25e4b6f17e278e11d9596b82'

    url 'http://dl.dafont.com/dl/?f=red_rocket'
    name 'Red Rocket'
    homepage 'http://www.dafont.com/red-rocket.font'

    font 'redrocket.ttf'
    font 'redrocket3d.ttf'
    font 'redrocket3dital.ttf'
    font 'redrocketacad.ttf'
    font 'redrocketacadital.ttf'
    font 'redrocketchrome.ttf'
    font 'redrocketchromeital.ttf'
    font 'redrocketcond.ttf'
    font 'redrocketcondital.ttf'
    font 'redrocketexpand.ttf'
    font 'redrocketexpandital.ttf'
    font 'redrocketgrad.ttf'
    font 'redrocketgradital.ttf'
    font 'redrockethalf.ttf'
    font 'redrockethalfital.ttf'
    font 'redrocketital.ttf'
    font 'redrocketlaser.ttf'
    font 'redrocketlaserital.ttf'
    font 'redrocketleft.ttf'
    font 'redrocketout.ttf'
    font 'redrocketoutital.ttf'
    font 'redrocketsemital.ttf'
    font 'redrocketsuperital.ttf'
end