cask 'dafont-earth-orbiter' do
    version :latest # created_at: 2016-05-16 00:00:00
    sha256 'e55855a2fa1c50b88f0d8d7a09f14ec461ec10068ea7cb4674a294a3c2576ef8'

    url 'http://dl.dafont.com/dl/?f=earth_orbiter'
    name 'Earth Orbiter'
    homepage 'http://www.dafont.com/earth-orbiter.font'
    license :unknown # TODO: change license and remove this comment; ':unknown' is a machine-generated placeholder

    font 'earthorbiter.ttf'
    font 'earthorbiter3d.ttf'
    font 'earthorbiter3dital.ttf'
    font 'earthorbiteracad.ttf'
    font 'earthorbiteracadital.ttf'
    font 'earthorbiterbold.ttf'
    font 'earthorbiterboldital.ttf'
    font 'earthorbitercond.ttf'
    font 'earthorbitercondital.ttf'
    font 'earthorbiterdeep3d.ttf'
    font 'earthorbiterdeep3dital.ttf'
    font 'earthorbiterengraved.ttf'
    font 'earthorbiterengravedital.ttf'
    font 'earthorbiterexpand.ttf'
    font 'earthorbiterexpandital.ttf'
    font 'earthorbitergrad.ttf'
    font 'earthorbitergradital.ttf'
    font 'earthorbiterhalf.ttf'
    font 'earthorbiterhalfital.ttf'
    font 'earthorbiterital.ttf'
    font 'earthorbiterlaser.ttf'
    font 'earthorbiterlaserital.ttf'
    font 'earthorbiterleft.ttf'
    font 'earthorbiterout.ttf'
    font 'earthorbiteroutital.ttf'
    font 'earthorbiterpunch.ttf'
    font 'earthorbiterpunchital.ttf'
    font 'earthorbitersemital.ttf'
    font 'earthorbitersuperital.ttf'
    font 'earthorbitertitle.ttf'
    font 'earthorbitertitleital.ttf'
    font 'earthorbiterxtrabold.ttf'
    font 'earthorbiterxtraboldital.ttf'
end