cask 'dafont-labtop' do
    version :latest # created_at: 2005-12-31 00:00:00
    sha256 '71ef2d23bf7946381ed022c84fe92954c2abb33a46032cbbcac5dedb768e1d05'

    url 'http://dl.dafont.com/dl/?f=labtop'
    name 'Labtop'
    homepage 'http://www.dafont.com/labtop.font'

    font 'Labtop Secundo/LABTSEBI.ttf'
    font 'Labtop Secundo/LABTSEC_.ttf'
    font 'Labtop Secundo/LABTSECB.ttf'
    font 'Labtop Secundo/LABTSECI.ttf'
    font 'Labtop Secundo/LABTSECS.ttf'
    font 'Labtop Secundo/LABTSECW.ttf'
    font 'Labtop Unicase/LABTOPU_.ttf'
    font 'Labtop Unicase/LABTOPUB.ttf'
    font 'Labtop Unicase/LABTOPUI.ttf'
    font 'Labtop Unicase/LABTUBI_.ttf'
    font 'Labtop Unicase/LABTUSW_.ttf'
    font 'Labtop Unicase/LABTUUP_.ttf'
    font 'Labtop Unicase/LABTUUW_.ttf'
    font 'Labtop Unicase/LABTUWD_.ttf'
    font 'Labtop/Labtop 3D.ttf'
    font 'Labtop/Labtop Candy Extra.ttf'
    font 'Labtop/Labtop Candy.ttf'
    font 'Labtop/Labtop Graphed.ttf'
    font 'Labtop/Labtop Outline.ttf'
    font 'Labtop/Labtop Superwide Boldish.ttf'
    font 'Labtop/Labtop Tartan.ttf'
    font 'Labtop/Labtop Thin.ttf'
    font 'Labtop/Labtop Underline.ttf'
    font 'Labtop/Labtop Upper Outline.ttf'
    font 'Labtop/Labtop Warp 1.ttf'
    font 'Labtop/Labtop Warp 2.ttf'
    font 'Labtop/LABTOP__.ttf'
    font 'Labtop/LABTOPB_.ttf'
    font 'Labtop/LABTOPBI.ttf'
    font 'Labtop/LABTOPI_.ttf'
    font 'Labtop/LABTOPW_.ttf'
    font 'Labtop/LABTOVS_.ttf'
    font 'Labtop/LABTSW__.ttf'
    font 'Labtop/LABTSWO_.ttf'
    font 'Labtop/LABTUND_.ttf'
    font 'Labtop/LABTUP__.ttf'
end