cask 'dafont-illumino' do
    version :latest # created_at: 2016-03-07 00:00:00
    sha256 '475621a90aa391a8478a1e286fc943db0acfcd5aa9dda3f689f14f20abacc819'

    url 'http://dl.dafont.com/dl/?f=illumino'
    name 'Illumino'
    homepage 'http://www.dafont.com/illumino.font'

    font 'illumino.ttf'
    font 'illumino3d.ttf'
    font 'illumino3dital.ttf'
    font 'illuminoacad.ttf'
    font 'illuminoacadital.ttf'
    font 'illuminocond.ttf'
    font 'illuminocondital.ttf'
    font 'illuminoexpand.ttf'
    font 'illuminoexpandital.ttf'
    font 'illuminograd.ttf'
    font 'illuminogradital.ttf'
    font 'illuminohalf.ttf'
    font 'illuminohalfital.ttf'
    font 'illuminoital.ttf'
    font 'illuminolaser.ttf'
    font 'illuminolaserital.ttf'
    font 'illuminoleft.ttf'
    font 'illuminoout.ttf'
    font 'illuminooutital.ttf'
    font 'illuminosuperital.ttf'
    font 'illuminoxtracond.ttf'
    font 'illuminoxtracondital.ttf'
end