cask 'dafont-y-files' do
    version :latest # created_at: 2016-03-14 00:00:00
    sha256 '1f4bb3b2462fc2851620e983fd19b6176513e65438e7a4a1ab606ad8302c16cb'

    url 'http://dl.dafont.com/dl/?f=y_files'
    name 'Y-Files'
    homepage 'http://www.dafont.com/y-files.font'
    license :unknown # TODO: change license and remove this comment; ':unknown' is a machine-generated placeholder

    font 'yfiles.ttf'
    font 'yfiles3d.ttf'
    font 'yfiles3dital.ttf'
    font 'yfilesbold.ttf'
    font 'yfilesboldital.ttf'
    font 'yfileschrome.ttf'
    font 'yfileschromeital.ttf'
    font 'yfilescond.ttf'
    font 'yfilescondital.ttf'
    font 'yfilesengarve.ttf'
    font 'yfilesengarveital.ttf'
    font 'yfilesepunch.ttf'
    font 'yfilesepunchital.ttf'
    font 'yfilesexpand.ttf'
    font 'yfilesexpandital.ttf'
    font 'yfilesgrad.ttf'
    font 'yfilesgradital.ttf'
    font 'yfileshalf.ttf'
    font 'yfileshalfital.ttf'
    font 'yfilesital.ttf'
    font 'yfilesleft.ttf'
    font 'yfilessemital.ttf'
    font 'yfilessuperital.ttf'
    font 'yfilestitle.ttf'
    font 'yfilestitle3d.ttf'
    font 'yfilestitle3dital.ttf'
    font 'yfilestitleital.ttf'
    font 'yfilesxtraexpand.ttf'
    font 'yfilesxtraexpandital.ttf'
end