cask 'dafont-athabasca' do
    version :latest # created_at: 2015-01-14 00:00:00
    sha256 '2b31eee69f5944ec888ce9d8da411e468cef15c4707ed0ca4317d26ba824d453'

    url 'http://dl.dafont.com/dl/?f=athabasca'
    name 'Athabasca'
    homepage 'http://www.dafont.com/athabasca.font'

    font 'athabasca-bd-it.ttf'
    font 'athabasca-bd.ttf'
    font 'athabasca-bk-it.ttf'
    font 'athabasca-bk.ttf'
    font 'athabasca-cd-bd-it.ttf'
    font 'athabasca-cd-bd.ttf'
    font 'athabasca-cd-bk-it.ttf'
    font 'athabasca-cd-bk.ttf'
    font 'athabasca-cd-eb-it.ttf'
    font 'athabasca-cd-eb.ttf'
    font 'athabasca-cd-el-it.ttf'
    font 'athabasca-cd-el.ttf'
    font 'athabasca-cd-it.ttf'
    font 'athabasca-cd-lt-it.ttf'
    font 'athabasca-cd-lt.ttf'
    font 'athabasca-cd-rg.ttf'
    font 'athabasca-eb-it.ttf'
    font 'athabasca-eb.ttf'
    font 'athabasca-el-it.ttf'
    font 'athabasca-el.ttf'
    font 'athabasca-ex-bd-it.ttf'
    font 'athabasca-ex-bd.ttf'
    font 'athabasca-ex-bk-it.ttf'
    font 'athabasca-ex-bk.ttf'
    font 'athabasca-ex-eb-it.ttf'
    font 'athabasca-ex-eb.ttf'
    font 'athabasca-ex-el-it.ttf'
    font 'athabasca-ex-el.ttf'
    font 'athabasca-ex-it.ttf'
    font 'athabasca-ex-lt-it.ttf'
    font 'athabasca-ex-lt.ttf'
    font 'athabasca-ex-rg.ttf'
    font 'athabasca-it.ttf'
    font 'athabasca-lt-it.ttf'
    font 'athabasca-lt.ttf'
    font 'athabasca-rg.ttf'
end