cask 'dafont-antilles' do
    version :latest # created_at: 2009-05-07 00:00:00 and updated_at: 2015-12-30 00:00:00
    sha256 '96c2c2c15db3fa48bf814768e2702ee58ed5224e88ecd8a0117c6da17462fb32'

    url 'http://dl.dafont.com/dl/?f=antilles'
    name 'Antilles'
    homepage 'http://www.dafont.com/antilles.font'
    license :unknown # TODO: change license and remove this comment; ':unknown' is a machine-generated placeholder

    font 'antilles.ttf'
    font 'antilles3d.ttf'
    font 'antilles3dital.ttf'
    font 'antillesacad.ttf'
    font 'antillesacadital.ttf'
    font 'antilleschrome.ttf'
    font 'antilleschromeital.ttf'
    font 'antillescond.ttf'
    font 'antillescondital.ttf'
    font 'antillesengraved.ttf'
    font 'antillesengravedital.ttf'
    font 'antillesexpand.ttf'
    font 'antillesexpandital.ttf'
    font 'antillesgrad.ttf'
    font 'antillesgradital.ttf'
    font 'antilleshalf.ttf'
    font 'antilleshalfital.ttf'
    font 'antillesital.ttf'
    font 'antilleslaser.ttf'
    font 'antilleslaser3d.ttf'
    font 'antilleslaser3dital.ttf'
    font 'antilleslaserital.ttf'
    font 'antillesleft.ttf'
    font 'antillesout.ttf'
    font 'antillesoutital.ttf'
    font 'antillesplat.ttf'
    font 'antillesplatital.ttf'
    font 'antillessemital.ttf'
    font 'antillessuperital.ttf'
end