cask 'dafont-guardian' do
    version :latest # created_at: 2008-05-17 00:00:00 and updated_at: 2015-09-19 00:00:00
    sha256 'd8ba2e3a1e0cbaa8853e5d55d51d72754cb78288c4468fc296742d30565c1b31'

    url 'http://dl.dafont.com/dl/?f=guardian'
    name 'Guardian'
    homepage 'http://www.dafont.com/guardian.font'

    font 'guardian2.ttf'
    font 'guardian23d.ttf'
    font 'guardian23dital.ttf'
    font 'guardian2acad.ttf'
    font 'guardian2acadital.ttf'
    font 'guardian2chrome.ttf'
    font 'guardian2chromeital.ttf'
    font 'guardian2cond.ttf'
    font 'guardian2condital.ttf'
    font 'guardian2expand.ttf'
    font 'guardian2expandital.ttf'
    font 'guardian2grad.ttf'
    font 'guardian2gradital.ttf'
    font 'guardian2half.ttf'
    font 'guardian2halfital.ttf'
    font 'guardian2ital.ttf'
    font 'guardian2laser.ttf'
    font 'guardian2laserital.ttf'
    font 'guardian2left.ttf'
    font 'guardian2out.ttf'
    font 'guardian2outital.ttf'
    font 'guardian2semital.ttf'
end