cask 'dafont-aircruiser' do
    version :latest # created_at: 2011-09-12 00:00:00 and updated_at: 2015-05-02 00:00:00
    sha256 '8ec162759881870cedeeb5be9a216e4cb5634e084339afa7e714119c2456baa8'

    url 'http://dl.dafont.com/dl/?f=aircruiser'
    name 'Aircruiser'
    homepage 'http://www.dafont.com/aircruiser.font'

    font 'aircruiser.ttf'
    font 'aircruiser3d.ttf'
    font 'aircruiser3dital.ttf'
    font 'aircruiseracad.ttf'
    font 'aircruiseracadital.ttf'
    font 'aircruiseracadlaser.ttf'
    font 'aircruiseracadlaserital.ttf'
    font 'aircruisercond.ttf'
    font 'aircruisercondital.ttf'
    font 'aircruiserexpand.ttf'
    font 'aircruiserexpandital.ttf'
    font 'aircruisergrad.ttf'
    font 'aircruisergrad3d.ttf'
    font 'aircruisergrad3dital.ttf'
    font 'aircruisergradital.ttf'
    font 'aircruiserital.ttf'
    font 'aircruiserlaser.ttf'
    font 'aircruiserlaserital.ttf'
    font 'aircruiserleft.ttf'
    font 'aircruiserlight.ttf'
    font 'aircruiserlightital.ttf'
    font 'aircruisersemital.ttf'
end