cask 'dafont-army-rangers' do
    version :latest # created_at: 2013-06-28 00:00:00
    sha256 '138a98f68e155d1b388b98c18e8356a29476015944d144ffeee1be79c3a7b6cf'

    url 'http://dl.dafont.com/dl/?f=army_rangers'
    name 'Army Rangers'
    homepage 'http://www.dafont.com/army-rangers.font'

    font 'armyrangers.ttf'
    font 'armyrangers3d.ttf'
    font 'armyrangers3dital.ttf'
    font 'armyrangersacad.ttf'
    font 'armyrangersacadital.ttf'
    font 'armyrangerschrome.ttf'
    font 'armyrangerschromeital.ttf'
    font 'armyrangerscond.ttf'
    font 'armyrangerscondital.ttf'
    font 'armyrangersengrav.ttf'
    font 'armyrangersengravital.ttf'
    font 'armyrangersexpand.ttf'
    font 'armyrangersexpandital.ttf'
    font 'armyrangersgrad.ttf'
    font 'armyrangersgradital.ttf'
    font 'armyrangershalf.ttf'
    font 'armyrangershalfital.ttf'
    font 'armyrangersital.ttf'
    font 'armyrangerslaser.ttf'
    font 'armyrangerslaserital.ttf'
    font 'armyrangersleft.ttf'
    font 'armyrangerssuperexpand.ttf'
    font 'armyrangerssuperexpandital.ttf'
end