cask 'dafont-terran' do
    version :latest # created_at: 2014-06-17 00:00:00 and updated_at: 2015-04-11 00:00:00
    sha256 '2fa3a72e4aa94038bca231e128091f66d48c5362028e4272a35d12062849a5ea'

    url 'http://dl.dafont.com/dl/?f=terran'
    name 'Terran'
    homepage 'http://www.dafont.com/terran.font'

    font 'terran.ttf'
    font 'terran3d.ttf'
    font 'terran3dital.ttf'
    font 'terranacad.ttf'
    font 'terranacadital.ttf'
    font 'terranchrome.ttf'
    font 'terranchromeital.ttf'
    font 'terrancond.ttf'
    font 'terrancondital.ttf'
    font 'terrandrop.ttf'
    font 'terrandropital.ttf'
    font 'terranexpand.ttf'
    font 'terranexpandital.ttf'
    font 'terrangrad.ttf'
    font 'terrangradital.ttf'
    font 'terranhalf.ttf'
    font 'terranhalfital.ttf'
    font 'terranital.ttf'
    font 'terranleft.ttf'
    font 'terranout.ttf'
    font 'terranoutital.ttf'
    font 'terransemital.ttf'
end