cask 'dafont-gunship' do
    version :latest # created_at: 2005-12-31 00:00:00 and updated_at: 2015-02-18 00:00:00
    sha256 'd3a7c3131d8cc9b66c6adcefb7cd629c1a932309606fe4642437e26f0ef7823a'

    url 'http://dl.dafont.com/dl/?f=gunship'
    name 'Gunship'
    homepage 'http://www.dafont.com/gunship.font'

    font 'gunship.ttf'
    font 'gunship3d.ttf'
    font 'gunship3dital.ttf'
    font 'gunshipacad.ttf'
    font 'gunshipacadital.ttf'
    font 'gunshipbold.ttf'
    font 'gunshipboldital.ttf'
    font 'gunshipcond.ttf'
    font 'gunshipcondital.ttf'
    font 'gunshipexpand.ttf'
    font 'gunshipexpandital.ttf'
    font 'gunshipgrad.ttf'
    font 'gunshipgradital.ttf'
    font 'gunshiphalf.ttf'
    font 'gunshiphalfital.ttf'
    font 'gunshipital.ttf'
    font 'gunshiplaser.ttf'
    font 'gunshiplaserital.ttf'
    font 'gunshipleft.ttf'
    font 'gunshipout.ttf'
    font 'gunshipoutital.ttf'
    font 'gunshipsemital.ttf'
    font 'gunshipsuperital.ttf'
end