cask 'dafont-zoomrunner' do
    version :latest # created_at: 2016-05-10 00:00:00 and updated_at: 2016-05-13 00:00:00
    sha256 '7ab4ad23043622583d03247ba24b1e78e3e7b4616472c5ab224494cc5f32975f'

    url 'http://dl.dafont.com/dl/?f=zoomrunner'
    name 'Zoomrunner'
    homepage 'http://www.dafont.com/zoomrunner.font'

    font 'zoomrunner.ttf'
    font 'zoomrunner3d.ttf'
    font 'zoomrunner3dital.ttf'
    font 'zoomrunneracad.ttf'
    font 'zoomrunneracadital.ttf'
    font 'zoomrunnerchrome.ttf'
    font 'zoomrunnerchromeital.ttf'
    font 'zoomrunnercond.ttf'
    font 'zoomrunnercondital.ttf'
    font 'zoomrunnerengrave.ttf'
    font 'zoomrunnerengraveital.ttf'
    font 'zoomrunnerexpand.ttf'
    font 'zoomrunnerexpandital.ttf'
    font 'zoomrunnergrad.ttf'
    font 'zoomrunnergradital.ttf'
    font 'zoomrunnerhalf.ttf'
    font 'zoomrunnerhalfital.ttf'
    font 'zoomrunnerital.ttf'
    font 'zoomrunnerlaser.ttf'
    font 'zoomrunnerlaserital.ttf'
    font 'zoomrunnerleft.ttf'
    font 'zoomrunnerpunch.ttf'
    font 'zoomrunnerpunchital.ttf'
    font 'zoomrunnersemital.ttf'
    font 'zoomrunnersuperital.ttf'
    font 'zoomrunnertitle.ttf'
    font 'zoomrunnertitleital.ttf'
end