cask 'dafont-liberty-legion' do
    version :latest # created_at: 2015-11-18 00:00:00
    sha256 '41830baf41e71d8a1afd4c97aab69fb4ecc3e021d73501e6dfdb1d3e8ce3db19'

    url 'http://dl.dafont.com/dl/?f=liberty_legion'
    name 'Liberty Legion'
    homepage 'http://www.dafont.com/liberty-legion.font'

    font 'libertylegion.ttf'
    font 'libertylegion3d.ttf'
    font 'libertylegion3dital.ttf'
    font 'libertylegion3dlaser.ttf'
    font 'libertylegion3dlaserital.ttf'
    font 'libertylegionchrome.ttf'
    font 'libertylegionchromeital.ttf'
    font 'libertylegioncond.ttf'
    font 'libertylegioncondital.ttf'
    font 'libertylegionexpand.ttf'
    font 'libertylegionexpandital.ttf'
    font 'libertylegiongrad.ttf'
    font 'libertylegiongradital.ttf'
    font 'libertylegionhalf.ttf'
    font 'libertylegionhalfital.ttf'
    font 'libertylegionitalic.ttf'
    font 'libertylegionlaser.ttf'
    font 'libertylegionlaserital.ttf'
    font 'libertylegionleft.ttf'
    font 'libertylegionout.ttf'
    font 'libertylegionoutital.ttf'
    font 'libertylegionsemital.ttf'
    font 'libertylegionsuperital.ttf'
end